---
version: "3.8"

services:
  backend:
    build: .
    command: fastapi run main.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: &env
      SERVICE_SECRET: secret
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment: *env

volumes:
  db_data:
